language: python
python: 3.6

cache:
  pip: true

stages:
  - coala
  - test

jobs:
  include:
    - stage: coala
      install: pip install coala-bears
      script: coala --non-interactive -V

    - stage: test
      install:
      - pip install -r requirements.txt
      - pip install -r test-requirements.txt
      script: pytest

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never
